language: java
jdk:
  - openjdk8

script:
  - ./gradlew build test jacocoTestReport
  - gradle test
  - ls build
  - gradle  run
##  - ./gradlew sonarqube  #  -Dsonar.organization=jamj2000-github   -Dsonar.host.url=https://sonarcloud.io 
after_success:
  - bash <(curl -s https://codecov.io/bash)


